//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace botApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BotEntities : DbContext
    {
        public BotEntities()
            : base("name=BotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BotData> BotData { get; set; }
        public virtual DbSet<RequestLog> RequestLog { get; set; }
        public virtual DbSet<NLPInfo> NLPInfo { get; set; }
        public virtual DbSet<CurInfo> CurInfo { get; set; }
        public virtual DbSet<ExRate> ExRate { get; set; }
        public virtual DbSet<BotTemplateAction> BotTemplateAction { get; set; }
        public virtual DbSet<BotTemplateMessage> BotTemplateMessage { get; set; }
    }
}
